[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle Next.js rewrites
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_server"
  status = 200
  force = true

# Ensure public directory is accessible
[[redirects]]
  from = "/uploads/*"
  to = "/uploads/:splat"
  status = 200
